class LabelColors{
  static Map<String, dynamic> colorLabels = {
    'pastelRed1' : 0xffffdddd,
    'pastelRed2' : 0xffffe5dd,
    'pastelOrange1' : 0xffffeedd,
    'pastelOrange2' : 0xfffff6dd,
    'pastelYellow1' : 0xffffffdd,
    'pastelGreen1' : 0xfff6ffdd,
    'pastelGreen2' : 0xffeeffdd,
    'pastelGreen3' : 0xffe5ffdd,
    'pastelGreen4' : 0xffddffdd,
    'pastelGreen5' : 0xffddffe5,
    'pastelGreen6' : 0xffddffee,
    'pastelGreen7' : 0xffddfff6,
    'pastelBlue1' : 0xffddffff,
    'pastelPurple1' : 0xffddf6ff,
    'pastelPurple2' : 0xffddeeff,
    'pastelPurple3' : 0xffdde5ff,
    'pastelPurple4' : 0xffddddff,
    'pastelPurple5' : 0xffe5ddff,
    'pastelPurple6' : 0xffeeddff,
    'pastelPink1' : 0xfff6ddff,
    'pastelPink2' : 0xffffddff,
    'pastelPink3' : 0xffffddf6,
    'pastelPink4' : 0xffffddee,
    'pastelPink5' : 0xffffdde5,
  };
}